// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoBrab5Z41319g9f-EY0eRcvWC7e7nvds',
    appId: '1:28785723116:web:f260754c3d28ce73cfc7c9',
    messagingSenderId: '28785723116',
    projectId: 'kibucu-hila',
    authDomain: 'kibucu-hila.firebaseapp.com',
    storageBucket: 'kibucu-hila.firebasestorage.app',
    measurementId: 'G-JVM69SQ9N0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG7gFGA1Cp0xSnFjD599K3xMsDT0xwO04',
    appId: '1:28785723116:android:e62fa1de29184471cfc7c9',
    messagingSenderId: '28785723116',
    projectId: 'kibucu-hila',
    storageBucket: 'kibucu-hila.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGrqExyBa6CVAp_i7yaZ8obhmlN26LvsM',
    appId: '1:28785723116:ios:3f6a531b48724697cfc7c9',
    messagingSenderId: '28785723116',
    projectId: 'kibucu-hila',
    storageBucket: 'kibucu-hila.firebasestorage.app',
    iosBundleId: 'com.example.myAppName',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoBrab5Z41319g9f-EY0eRcvWC7e7nvds',
    appId: '1:28785723116:web:eaf3ed0e0dd0a329cfc7c9',
    messagingSenderId: '28785723116',
    projectId: 'kibucu-hila',
    authDomain: 'kibucu-hila.firebaseapp.com',
    storageBucket: 'kibucu-hila.firebasestorage.app',
    measurementId: 'G-PB5FBL939Q',
  );
}
